amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.01 # 0.05
    alpha2: 0.01 # 0.05
    alpha3: 0.05 # 0.05
    alpha4: 0.05 # 0.05
    alpha5: 0.05
    base_frame_id: "base_footprint" # base_link # "base_footprint" - default 
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: False
    global_frame_id: "map"
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 20.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 360
    max_particles: 5000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 1.0 #0.5
    set_initial_pose: True # True
    always_reset_initial_pose: False
    sigma_hit: 0.2
    tf_broadcast: True
    transform_tolerance: 0.1 #0.1
    update_min_a: 0.07
    update_min_d: 0.07
    z_hit: 0.95
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

  
map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "" 

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True